### ISSUE TITLE
ModuleNotFoundError: No module named 'apex'

### ISSUE THREAD

**Issue by asif-nuaa** [DengPingFan/SINet#45]
Following error appear when I try to run MyTest.py

D:\asif\Projects\OtitisNet2\Scripts\python.exe D:\asif\Projects\OtitisNet2\SINet-master\MyTest.py 
Traceback (most recent call last):
  File "D:\asif\Projects\OtitisNet2\SINet-master\MyTest.py", line 9, in <module>
    from Src.utils.trainer import eval_mae, numpy2tensor
  File "D:\asif\Projects\OtitisNet2\SINet-master\Src\utils\trainer.py", line 5, in <module>
    from apex import amp
ModuleNotFoundError: No module named 'apex'

Process finished with exit code 1

-------------------------

I try to install this using --> pip install apex, but their is no such module. How to fix it?

**Comment by Jackie-Li-0228** [comment]
The README.md file has the information. But when I installed it, I got an error message saying that many package dependencies require Python version 3.7 or 3.8, but the author specified Python 3.6 at the time.
